FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.com /etc/nginx/conf.d/dafault.conf
COPY --from=builder /app/build /usr/share/nginx/html
